version: '3.3'

services:
  app:
    build: .
    container_name: app
    ports:
      - "6000:6000"
#    environment:
#      - DEFAULT_PORT=${DEFAULT_PORT}
#    ports:
#      - "${DEFAULT_PORT}:${DEFAULT_PORT}"

  nginx:
    image: nginx:latest
    container_name: nginx
#    environment:
#      - DEFAULT_PORT=${DEFAULT_PORT}
    volumes:
#      - ./.env:/etc/nginx/.env
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
#    command: /bin/sh -c "envsubst '\$DEFAULT_PORT' < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
