version: '3.3'

services:
  app:
    build: .
    container_name: app
    ports:
      - "6000:6000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
