FROM nginx:latest

RUN apt-get update && apt-get install -y gettext

COPY nginx.conf.template /etc/nginx/nginx.conf.template
COPY docker-entrypoint.sh /docker-entrypoint.d/

RUN chmod +x /docker-entrypoint.d/docker-entrypoint.sh
